
// Note: API_KEY should be set in the environment variables (e.g., process.env.API_KEY or import.meta.env.VITE_API_KEY)
// For this example, we'll read it in App.tsx. Ensure it's configured in your deployment.

export const INVESTMENT_LINK = "https://www.startengine.com/alpharose";

export const INITIAL_AI_GREETING_TEXT = "Hello! I am AlphaRose AI, your guide to AlphaRose Therapeutics. I can provide information based on our business plan and latest updates. How can I assist you today regarding potential investment or learning more about our mission?";

// Full Business Plan Text (Extracted from OCR)
export const BUSINESS_PLAN_TEXT = `
ALPHA ROSE THERAPEUTICS
A Precision Medicine Company
BUSINESS PLAN (confidential)

Executive Summary

AlphaRose Therapeutics: Revolutionizing Drug Development for Ultra-Rare Pediatric Diseases
AlphaRose Therapeutics, a spin-off of To Cure A Rose Foundation, is a precision medicine company with a mission to develop life-saving treatments for children with ultra-rare genetic diseases.
Vision: Where every human has access to personalized genetic treatments
Mission: Develop life saving technologies that treat children with ultra rare genetic diseases at scale, unlocking their full potential of life.

Innovative Approach
• Focus on Ultra-Rare Diseases: Addresses the unmet medical needs of children with ultra-rare genetic diseases (50-500 diagnosed patients) that are often neglected by traditional drug development.
• RNA Therapeutic Technology: Leverages the low cost and scalability of RNA therapeutics, specifically Antisense Oligonucleotides (ASOs), to develop targeted treatments for smaller patient populations.
• Personalized Medicine Platform: Aims to create a scalable platform for rapid, personalized drug development, starting with Rosiphersen, its lead ASO drug candidate.

Business Model
• Phased Approach: The business plan outlines a phased approach with key milestones:
  • Phase 1 (2025-2028): Focus on advancing Rosiphersen through clinical trials and commercialization, generating initial revenue, and establishing data partnerships for the RINAE.Al platform.
  • Phase 2 (2027-2030): Build a commercial platform for ultra-rare disease treatments, expand the drug pipeline, and develop the RNAR-1 robotics platform.
  • Phase 3 (2030-2035): Implement the automated RNAR-1 lab for rapid drug development and scale the RINAE.Al platform.
  • Phase 4 (2033-2040): Achieve global scale and develop SaaS products based on the RINAE.Al platform.
  • Phase 5 (2035): IPO
  • Phase 6 (2040-2045): Develop a fully productized personalized medicine platform.
• Sales and Marketing: Initial focus on developing and commercializing lead product, Rosiphersen, with 100-700m in peak annual revenue, followed by B2B2C sales for later products. Marketing strategy centers around genetic sequencing companies, patient organizations, partnerships, and innovative science.
• Financial Projections: Revenue projections based on current regulatory paths and drug pricing for ultra-rare diseases, with significant revenue potential in later phases.

Core Values and Principles
AlphaRose is guided by patient-centricity, innovation, collaboration, and a commitment to ethical business practices. The company's success hinges on navigating regulatory hurdles, securing partnerships, and maintaining a strong focus on its core values while driving innovation in the ultra-rare disease space.

Our Story
AlphaRose Therapeutics Inc. has the potential to impact millions of children and thousands of diseases across genetic disease, cancer, pandemics, epidemics, and many other biological threats to our society. Our technology will generate billions of dollars in revenue, and is poised to be the most advanced rapid personalized drug development system in the world, introducing therapies at an unprecedented scale and speed. We want to revolutionize drug development to save and protect our most precious resource, our children, who are currently suffering and dying from our lack of innovation in the hundreds of millions. We see this as a global civil rights issue that can be solved through technology. The science currently exists to accomplish the mission of AlphaRose, but the systems, business models, and regulatory do not. We will change that.
AlphaRose is a spin-off company of To Cure A Rose Foundation. It has emerged from a father's devotion to his daughter, Rose, who was diagnosed with a rare neurological genetic disease from mutations in the gene HNRNPH2, that currently has no cure. Rose had reached the limits of what our current healthcare system could do for her. Realizing that Rose and millions of children in similar situations would be unable to live independently without genetic intervention, Casey McPherson founded the non-profit organization "To Cure A Rose Foundation." A year and a half later, he co-founded the company, “Everlum Bio' as a lab to do preclinical work for families that had these ultra-rare indications. Through an ongoing partnership between both organizations, Casey assembled a team of scientists and developed the first proof of concept drug for HNRNPH2, "Rosiphersen." Now, the team seeks to apply the technologies, expertise, partnerships, and vision they have acquired to make a tangible impact in the lives of children with ultra rare genetic disease. We must revolutionize our healthcare system by bringing these treatments to market at scale.
Currently, more than 200 million children face the challenges of rare genetic diseases like Rose's, with a staggering 95% of these conditions lacking any treatment options. This is primarily because traditional drug development has been built upon a population-based approach, and most of these diseases are considered ultra-rare. However, AlphaRose believes there is an opportunity to save these children and tap into a new market for a scalable, biologically tailored genetic treatment platform. While rare neurological diseases are the primary focus, AlphaRose's technology licensing opportunities may also extend to conditions such as Alzheimer's, ALS, cancer, as well as products in the Al, software, and neural computing sectors.
Throughout his team's journey, McPherson and company have devised an innovative approach to building and deploying medicines for smaller populations. They achieve this by leveraging the low cost and scalability of RNA therapeutic technology. Most companies grapple with large amounts of data, cell lines, and massive patient cohorts in trials, which hinder the scaling of drugs for multiple diseases and create a huge initial cost burden. We have discovered that most diseases have subsets that warrant more personalized approaches. Without systems in place to address these unique considerations, the process becomes onerous, costly, and often ends up with a less impactful drug. AlphaRose has already made significant strides in developing such systems. By utilizing regulatory incentives specific to rare diseases, along with RNA technology and smaller data sets from these populations, AlphaRose envisions reshaping our current drug development practices. Conventional boundaries can be overcome, and processes like drug design, drug screening, and batch trials are capable of being scaled. The company's initial proprietary technology, Rosiphersen, has been built on the platform of Antisense Oligonucleotides (ASOs). ASO technology is poised to solve many of the ultra rare disease issues. It is one of the few genetic platforms approved for chronic administration by regulatory bodies. With manufacturing costs one-tenth that of gene therapy, AlphaRose sees ASOs as the ideal solution to scale, offering the potential for profit margins for smaller populations. Success stories like Spinraza have already paved the way for a company like Alpha Rose. As well as new investments into this technology for personalized treatments by Google Ventures, Third Rock Ventures and others, demonstrating that companies like AlphaRose can bring significant change to an industry that has not served its constituency for several decades.

AlphaRose Team and Structure
Board of Directors
• Alan Walts - Co-Founder & Executive Chairman - Alan most recently managed Genzyme's corporate venture fund, Genzyme Ventures (now Sanofi Ventures), where he was responsible for identifying and closing several new investments, and for managing a portfolio of direct and LP investments. Alan earlier led business and corporate development activities in Genzyme's Therapeutics business, where he initiated and executed a number of transactions and new business initiatives that led to several innovative marketed products. Alan's roles at Genzyme also included President of Genzyme Pharmaceuticals and head of chemistry and biopolymer research. Alan received a Ph.D. in chemistry from MIT in 1985, carried out post-doctoral research in biochemistry at MIT with Professor Christopher Walsh, and completed the executive Program for Management Development at Harvard Business School in 1993. In addition to his role at Advent, Alan currently works as a business advisor to Belinda Termeer, the widow of Genzyme's former Chairman and CEO, Henri Termeer, and is a founder and Director of The Termeer Foundation. Alan has co-founded several companies with Advent and is also a board member and advisor to several life science companies.
• Belinda Termeer - Co-Founder & Board Member - Belinda Termeer is the President, Co-Founder, and Member of the Board of Directors of The Termeer Foundation. She is also the head of the Termeer family office. Belinda brings unparalleled passion to The Termeer Foundation, as well as significant experience serving on boards of directors for both nonprofit and for-profit organizations, both within and beyond the life sciences industry. In 1998, together with her late husband, Henri Termeer, she started the Termeer family office and has since managed its assets. In 2011, she and Henri established the Henri and Belinda Termeer Center for Targeted Therapies at Massachusetts General Hospital with the goal of developing a best-in-class center for personalized medicine, building on Henri's work as Genzyme's CEO focused on rare diseases.

Executive Team
(CEO, COO, and CSO cv's accessed in data room)
• Casey McPherson (Co-Founder / CEO) - Casey is responsible for executing the overall vision of the company, company culture, and executive team management. He fosters a culture of creativity, urgency, team work, accountability, and efficiency. Casey is also responsible for managing the executive team, partnership building, fundraising, and communicating our milestone objectives internally and externally.
• Masako Nakamura (COO & President) - Masako provides operational and business leadership, including overseeing the clinical development plan of Rosiphersen, as well as all other assets in the pipeline. She will oversee the clinical development lead and team, and be responsible for the management and execution of our clinical and commercialization plans. She, with the CSO, will submit yearly grants to apply for non-dilutive capital funding for additional projects.
• Robert Cabrera Ph.D. (CSO) - Robert Cabrera is an esteemed scientist from Baylor College of Medicine with a background in drug development and neuroscience. He oversees all preclinical work for new indications, our new technology platforms we're developing, as well as certain science during clinical programs, like biomarkers and toxicity and efficacy reports in vitro and in vivo.
• Jeffery Brown (Head of R&D) - Dr. Jeffrey Brown is a seasoned biotech leader with over 20 years of preclinical drug development experience. Throughout his career, Jeffrey has built several drug discovery platforms focused on RNA, AAV, and small molecule therapeutics across multiple organizations including Pfizer, Bristol-Myers Squibb, Alexion, Voyager Therapeutics, and Wave Life Sciences. With a focus on moving therapeutics from concept to clinic, Jeffrey has successfully advanced multiple preclinical programs to drug candidates, with some reaching clinical trials. Jeffrey received an MBA from Suffolk University and Ph.D. in Pharmacology and Toxicology from the University of Utah. Following his Ph.D., Jeffrey completed post-doctoral training at Harvard Medical School and Boston University Medical Center. Combining his drug discovery experience with his passion for helping patients affected with rare disease, inspired him to establish Scientific Foundation LLC, an organization dedicated to helping families, patients and biotech start-ups navigate the challenges of preclinical drug development. In addition, Jeffrey currently serves as Chief Scientific Officer at Sensorium Therapeutics and is a contributing member of the Board of Trustees for the Huntington Disease Society of America.

PBC Delaware Corp
AlphaRose is a Public Benefit Corporation (PBC). We believe that the impact on a patient's life is what ultimately gets us to the finish line. A PBC ensures that we are fiscally responsible to both our stakeholders and our shareholders, allowing a more complete alignment for all our constituents. We also believe it attracts the type of investors, partners, and advisors that recognize the value of making a huge impact on these children as well as making a significant profit. Many successful invested companies are PBCs, and we are unapologetically proud to become one of them.

Sales and Marketing
Our Products
Our initial biologic line of drugs will be Antisense Oligonucleotide (ASO) therapeutics for ultra rare pediatric neuro diseases, with no current treatment on the market, and in the 50 - 500 currently diagnosed range. Our ASOs will be primarily MOE and LNA backbone chemistries that have already seen approval in the neuro space. There are elements that make our product special. It is the only non-permanent genetic platform technology that provides a higher safety profile, and is chronically administered. The smaller patient base is a space that very few companies are in, and gives us four major advantages.
1) We will have time to corner the market with less competition.
2) It provides us a constraint to create technologies to increase production and revenue.
3) Regulatory bodies are more willing to be creative with current drug safety and clinical trial protocols.
4) There are a number of Orphan Drug Designations and unmet need incentives that make these products incredibly attractive for both shareholders and our customers.
Rosiphersen is our primary focus over the next 2-3 years as our first biologic product. Following Rosiphersen will be additional biologics, robotic and software technologies, and other intellectual properties we will exploit as we build our platform. Ultimately, we want our process to be the final end product.

Place
AlphaRose has offices in Austin and Houston, TX, Boston, MA, and potentially one other location based on needs. Our biologics will be positioned to be developed and commercialized internationally, and our partners will have access to regional locations.

Promotion
Our communication objective for our brand will be around patient stories, partnerships, and cutting edge innovative science. We will use videos, pictures, social media, and ad campaigns. We will actively look for, and announce, new partnerships with others where there is mutual benefit. We have ongoing partnerships with To Cure A Rose Foundation, NCATS, and other organizations.. For commercialization and patient acquisition, our drug promotion will rely on lean marketing strategies, focusing on our product access being available at initial diagnosis via the main genetic testing companies like GeneDx, Invitae, and others. Typically, all genetic diagnoses come through a whole exome or whole genome report. These reports allow companies and researchers to add their information around a gene of interest. We would be able to add our treatment and support for those patients in those diagnoses. Our model focuses on promoting our therapeutics to those getting a diagnosis, not on convincing those that haven't to get a genetic test, which saves an immense amount of time and money.
Specifically for patient acquisition, we will be partnering with new companies like Probably Genetic and Luna. Internally we will be working with patient groups, applied behavior analysis therapy organizations, pediatric neurologists, and physical, occupational, and speech therapists.

Price
Rosiphersen will be positioned to be at maximum net value to our company by establishing a robust patient registry, biomarker, and safety profile. The nature of this IP package will be late stage, meaning its risk profile, and potential revenue will be well established. Our goal is to commercialize this treatment as a company.
Est. commercialized Rosipherson prices: 400 - 600k a year (per patient)
Our prices are based on comparable rare disease drug pre commercialization sales, and revenue history of similar technologies for commercialization, like Spinraza. Rosipherson's value, and the success will be largely dependent on four things:
• Animal tox/efficacy data (pre trial)
• Human data (during trial)
• Pediatric Review Voucher (post phase 1/2)
• Patient numbers (ongoing)
• Market Exclusivity
For commercialization value, these data points above, our plan to scale with our platform approach that capitalizes on technological efficiencies, and our ability to market to the “untouched” ultra rare disease markets are big value creators.
Our strategies with all of these data points are key to creating the highest value possible for our company's products.

Total Product Experience
The primary features and auxiliary dimensions of these rare disease biologics in addition to our future tech will be centered around refining more personalized therapeutic development processes, with a heavy emphasis on real patient impact from the treatment, and patient access to these treatments.

Industry Overview
Snapshots of the global ASO/RNA market
Global Antisense Oligonucleotide Therapeutics Market Research Report
CAGR (2023-2031): 13.15%
Market Size: US$ 26.97 Bn (2022)
Largest Region: North America
(Additional market data and competitor mentions from pages 9-11 are noted but not fully transcribed for brevity in this constant, the AI should refer to general market growth and key players like Ionis, Sarepta, Biogen, Alnylam if relevant from this section).
Snapshot of Spinraza sales (similar technology as our drugs). Rosiphersen is plus/minus one sixth of the size, but our platform of drugs would surpass these numbers in 6 years. Other things to note are that Spinraza (ASOs) significantly out performed Zolgensma (gene therapy) for Spinal muscular atrophy from a revenue standpoint. This also shows sustainable revenue over time.

Analysis
ASO Market
We see a significant increase in growth for the ASO market. We think this is because ASOs have a lower barrier to entry from a cost and safety perspective, as opposed to the $1.5m cost of a gene therapy. They are easier to manufacture and less costly to produce. We also see the impact ASOs have made in multiple healthcare spaces, as well as the chronically administered model, allowing for more revenue over time allowing this technology a greater approval in more countries because of these aspects.
While a considerable number of competitors exist, many are developing new chemical modifications, as opposed to creating any technological efficiencies. For the drug developers, most are licensing a technology from an academic institution or another company in order to commercialize, also not owning the pipeline or innovating on the system to scale, but developing an already established technology. Lastly, because we're focused on smaller indications, we think this list gets considerably smaller, if not non-existent, as most or all of these companies are still focused on traditional “population medicine” based approaches.

Rare Disease Market
Because of the high cost of gene therapy, traditional development, regulatory requirements, and commercialization strategies, many companies in the rare disease space have dropped or severely limited their programs. We also saw a downturn in rare disease investment in 2021, as the cost of capital increased. We see this as an opportunity to build a company with systems focused on smaller indications, and using that to our advantage as opposed to it being a hindrance.

Barriers To Entry
ASO Chemistry: While inexpensive in comparison to other drug technologies to make, RNA therapeutics can be easily misunderstood and developed incorrectly. There is an “art” to the science with this technology that is still being understood. This art is only well known by a handful of scientists, ones that we work with already in the rare disease space. Toxicities in this technology are largely due to design, off targeting effects, and dose dependence. There have been many incredibly recent scientific breakthroughs with knowing the characteristics of these features, that are allowing us to avoid many of these issues very early on in the design process. These issues are fundamental to the building of our data sets, RINAE.Al, and our deep understanding of the current strategies.
Animal Toxicity Models: Animal models have made developing genetic biologics incredibly arduous, expensive, and time consuming. Their toxicity data are often inaccurate data sets for human comparisons. While they may have worked better with other technologies, these models do not exhibit sustainable accurate data to de-risk genetic treatments into a platform. We see our RINAE.Al, parallel tox studies, and Master File work as crucial to removing this expensive and time consuming barrier to our technology.
Regulatory: Regulatory bodies and protocols have been built on population based drug approvals. Their procedures are the primary expense of developing our drugs for market. It is a piece of our plan that we cannot control, and will battle the constraints based on their approvals or disapprovals of our proposed plans. But we feel confident, based on historic recent FDA guidance, that they are open to good science helping to pave the path towards more personalized and faster trials and approvals.

The Future of the Market
We believe personalized treatments are the future of healthcare, covering almost all cancers, neurological, and genetically diagnosed diseases. The science points to it. We also see the economic burden of rare disease, as well as the incredibly expensive price tag on curative treatments as being a massive problem we have to solve as a society. This is largely why AlphaRose exists, but the question arises “Can we make money?" We have done an extensive amount of research on this question for over two years. We've determined, based on working intimately with multiple genetic treatment modalities, that ASO's are the only current genetic treatments that have the potential of sustainable revenue as a drug for as little as one person. ASOs are scalable in that they are largely designed in-silico, synthetically printed, inexpensive to make, and chronically administered. We see these unique qualities similar to a software services technology that uses subscription services. The major barrier to this new market is the regulatory animal safety studies and antiquated clinical trial requirements. In early 2023, the FDA released new guidance documents reporting that they are willing to move away from animal models with significant relevant data to argue against it. With Covid, we've seen regulators approve “batch trial” strategies with Moderna and others. This gives us the indication that genetic treatments will become more of a “procedure” than a drug development. Imagine genetic medicines being a “molecular surgical” procedure instead of an approved drug. We see the future of medicine. These types of technologies will be used in hospitals as point of care diagnosis and treatment, revolutionizing human health and longevity. But the current business model in biotech and pharma is not built to support this type of platform, as the majority of revenue is acquired by population based sales around a single IP of a drug/compound.
The changes we must make to usher in this future are finally in our grasp. The first is regulatory. We have watched the FDA change their regulatory requirements with Milasen, the first personalized therapeutic, COVID, and other trials where they had good science to back up new arguments. We have partnered with an Al company, WEAVE, to utilize all science and past INDs to help us begin to make these new arguments. The second big change is access to genes, and moving to process IP, not drug IP. Where we see the first big legal or policy change indication here is around sequence based patents. Currently and unethically, companies are filing “blanket patents" on sequence design for ASO's and other RNA drugs. This allows them to corner a gene and render it impenetrable from any other competitor from an IP standpoint. We are certain that these patents will be overturned and get rejected in the very near future. We base this strong assumption on the Supreme Court rulings against patents on a gene in AMP vs Myriad, or a section of computer code in Google vs Oracle. Not to mention the millions of children that have suffered and died because of shelved or trapped IP of these curative treatments for this very reason. We see government officials beginning to wake up to the injustices this type of patent strategy is creating. Scalable RNA platforms will be poised to be the first ever genetic treatment process approvals by regulatory agencies for genetic diseases.

Market Penetration
Our customer profile includes families with children just diagnosed with any of the diseases we have therapeutics for or are developing. These families will primarily exist in the US, Canada, EU, Australia, and Asia. For more developing countries, we will be creating an access team that works with the local government, insurers, and nonprofits to make sure they have access to these treatments at an appropriately priced cost. The unique marketing model we are developing does not require expensive commercials and marketing to find these rare patients. We will rely on partnerships with multiple genetic testing companies, foundations, and social media marketing, significantly reducing our customer acquisition costs and allowing us to be more targeted in our approaches.
Market Segmentation
Main Customer Base:
Geographic: EU, US, CA, ASIA, AUS,
Demographic: 1-7yrs old, access to hospital and general practitioner, at least one working parent
Psychographics: Highly motivated families, typically enrolling their children into extracurricular activities, they have health insurance, and have utilized resources like Early Childhood Intervention, Applied Behavioral Analysis, and others.
Secondary Customer Base: As a PBC and due to the low cost of manufacturing, we will always make sure our therapeutics have a route to sustainable availability for third world countries, low income families, and families without insurance.

Product Plan
Our therapeutics will be used to intervene in the destructive nature of pediatric genetic diseases. They will either downregulate a toxic gene, upregulate a loss of function, or restore protein development within a particular gene. They slow the progression, stop the progression, and/or potentially rescue abilities when treated early enough in a child's development. We will utilize creative marketing strategies and partnerships to alert patient families to the availability of these treatments. It will require a marketing and commercialization team, as well as a reimbursement team to make sure patients are covered. The drugs will be manufactured, packaged, and distributed initially by our contract research partners, with the intention of eventually bringing end to end development and deployment in house.
Features our customers will be seeking include: Access to administration location, Insurance approval, A positive change in their child's behavior or disease, Quality communication from company, Funding, Referrals, Resources, Diagnosis and prescription assistance.
How we will create these features: Patient facing culture in our staff, Training for doctors located in new patient geographic location, A highly skilled insurance team to work with patients and hospitals, A science team that makes impactful therapeutics, A direct line to our customer care team.

Unique Selling Proposition
Our unique selling proposition is access to treatments millions of patients would never have with our current healthcare business model. We will in most cases be the only approved treatment that is on the market., Our products will receive Orphan Designation providing accelerated approvals as well as the the Pediatric Review Voucher providing a lucrative revenue stream by it long history of being purchased by large pharmaceutical companies., We will be poised to receive any rare and ultra rare disease incentive available to biotech. We will be extremely valuable to the scientific community, and healthcare as a whole, in moving science forward for the diseases, personalized medicine platforms, and most importantly the therapeutic and lifestyle benefits to the patient/customers. We provide this value by proving our new model is possible, profitable, and impactful.
Competitors should be “big pharma” but they will not enter into this space. For other rare disease biotech companies that we may compete with they most likely will be gene therapies, which typically are arduous to create, cost more money, and will be more difficult to access due to the cost. In the future, if a competitor comes out with a new technology that is less expensive or less invasive, then our therapeutic would either lose market share, or be included as a combination therapy with the new drug. We see our platform as being able to adopt Base Editing, Prime Editing, and the other future technologies that have scale potential. It is very likely that more companies will enter this market over the next decade. Our challenge will be to offer the fastest turnaround time for a new drug, the most impact in the patient's lives, and the best customer/patient support possible.

Product Life Cycle
ASO's for pediatric neurological diseases have historically spent half their time in clinical trials, but have significant market benefits for exclusivity. The preclinical development can potentially be done in as little as 6 months. The regulatory required safety studies can be done in as little as 6 months. But the clinical trials will last for at least a year and up to 4 years. In the United States, with Orphan designation (rare disease) our drugs will be awarded the Priority Review Voucher from the FDA, (worth $75-100m), and will have seven years of exclusivity in the US and 10 years in the EU, from the point it is approved for commercialization. (Chart on page 17 shows ASO Lifecycle cost vs revenue projections over 9 years, with revenue peaking at Y4 then declining).

Pricing Strategy
Because ASO's are relatively inexpensive to manufacture, and ultra rare disease marketing is less expensive by utilizing diagnostic companies, we will base our pricing on the models already established by other competitive brands, like Spinraza. Starting between 400k-600k a year pricing strategy which would meet not only the payers approval, but would also make it easier to access for patients without having a larger up front payment, like Spinraza, for the first year of injection. Then we would drop the price as competitors entered the space, and our exclusivity ran out. Each patient would generate 5 - 20 years of revenue, depending on the market and other available therapeutic options. Taking a conservative revenue projection approach, we estimate an average of 7 years, with a minimum of 3.5m per patient depending on the market. These amounts would significantly increase if no alternative treatments ever came available. We will also offer significantly lower prices to developing countries to provide access, but considering our low costs to manufacture, even if these would continue to be profitable. We will consider a percentage of our drug to be discounted or free for many of our secondary markets through an application process, where insurance is not available, will not cover, or has been rejected.

Operational Plan
Our plan will be rolled out in Phases. Being as we are creating a system and a model that does not currently exist, we want each part of our roll out to be sustainable, profitable, and have a solid foundation before moving to the next phase.
2025 - 2028 Phase 1: Map Making and Revenue Generation
Milestones: Get Rosipherson, or our first drug into the clinic and and commercialize with 100m PRV. Have 3 - 5 other ASO targets validated in preclinical development. Establish RINAE.Al foundation - Data partnerships and data sets being established and generated by animal tox contract research organizations (CRO), our National Center for Advancing Translational Science (NCATS) brain organoid program, and our preclinical and clinical programs. A commercial plan with established partners for marketing future ultra rare drugs. Initial design of our robotics platform (RNAR-1) started once the first drug is approved.
2027 - 2030 Phase 2: Commercial Platform
Milestones: Commercial team to go to market with our 2nd and 3rd drug. Achieve a minimum of a 35% margin with each patient in major markets including direct and associated costs. Accomplish a vetted and validated commercial model for ultra rare disease. RNAR-1 planning and design complete. RNAR-1 proof of concept modular pieces acquired, created, and/or built. Good Manufacturing Process (GMP) manufacturing plans for in-house production incorporated. 6 drugs in the pipeline with at least 2 licensed or commercialized. RINAE.AI Design tool, storage, and safety database fully integrated.
2030 - 2035 Phase 3: Automated Robotics Platform (RNAR-1 Lab)
Milestones: Initial RNAR-1 lab from design to GMP manufacturing built. A 20x fold increase in preclinical production. 6 months from drug design to IND. Turn our tox data sets into usable data and make a batch trial / Master File argument for our drugs. Beta version of internal RINAE.Al platform. 2 commercialized or licensed drugs a year. RINAE.AI integrated with a shared database across academic institutions and companies to scale datasets.
2033-2040 Phase 4: Global Scale and Saas Product
Milestones: FDA or MHRA approves a batch trial or Master File IND based upon our tox data sets. Parts of RINAE.Al becomes licensable to companies as an income stream. Build out considerations for collecting clinical and preclinical data for other genetic treatment technologies. Integrate into the leading software platforms of the sector. License RINAE.Al to other biotech and pharma companies with incentives in order to build larger data sets.
2035 Phase 5: IPO
2040 - 2045 Phase 6: Personalized Genetic Medicine - Productize the process
Milestones: Reduce our entire end to end system with RINAE.Al and RNAR-1 into our proprietary packaged product that can exist as one machine, consider modifications for other genetic platforms, RNA therapeutics, gene therapies, base and prime editing. Partner with diagnosis, diagnostic, and medical data management companies to create full stack experience. Create a patient experience from diagnosis to treatment utilizing our system and treating an n=1 patient faster and cheaper than anyone ever in history, and showing it to be profitable. Sell/license the system to pharma and hospitals for point of care drug development, and accredited centers.

Synopsis
Our first major milestone is getting Rosipherson through clinical trials and into the market. We see this as also being the milestone in which we reach our first set of revenue goals by being a revenue generating commercial company. During this development, in parallel, our preclinical team will spin up three additional proof of concept medicines for similar indications. Our learnings from Rosiphersen and revenue from initial commercialization, will help us begin to carve out our platform pieces we develop.

Failure
We know that any revolutionary technology is built by grit, failure, and iteration. While we set aggressive goals, we also recognize the potential unforeseen roadblocks. If Rosiphersen fails at IND enabling studies or in the clinic, we have multiple lead candidates we can replace it with, giving us multiple chances to succeed. If all of those fail, we will have three other preclinical proof of concepts ready to replace Rosipherson with, staying on course with the trajectory of our first revenue target.
Our guiding principles with creating new systems will be three major components:
1. Planning Phase: Mentors and experts contributing and validating the plan. Team responsibilities. Large goals broken down into smaller ones.
2. Execution Phase: Lean Startup Mentality - first MVP has only what you need. Utilize accountability and task setting to accomplish large goals. Create, test, iterate, fix, iterate, fix again.
3. Collaborate: Extreme ownership - always feel responsible for a project. Best Idea Wins - doesn't matter who it comes from. Be Nice - Teams make it work, no one operates as a lone wolf.

Final Future Platform
With each drug that is developed, and by applying creativity, partnerships, and innovation to these Phases, we will build the world's most advanced Al and automated robotics wet/dry lab from design to gmp manufacturing over time. We know that each piece of technology we need exists already in some form, but putting all of them together to run as one unit will be the innovative part, as well as how and what data we collect to establish predictive models in the Al space. As an example, RINAE is a definitive structure that leading ASO scientists follow in their experiments. RNAR-1 is modeled after what has already been automated and scaled in the small molecule space. We see our lab getting smaller and smaller, much like the modern computer did. Allowing us to sell or license our “point of care drug development platform" to hospitals, research facilities, and biotechs in the future as an entire package point of care drug development.

Organizational Plan
When creating something new as a team, we believe a company culture is crucial to team driven innovation. Positive reinforcement, deep relationship building, and transparent accountability will be key in building a culture we believe will create access for medicines for these children. Our partnership with To Cure a Rose Foundation will keep the patients in the forefront of our culture, ultimately leading to a truly patient-centric culture.
Core Values and Principles
Our Core Values: Patients are our North Star. Grow - Learn how to Be Better, and Make It Better. Fail Fast and Take Extreme Ownership. Execution Plus Creativity Equals Value. Servant Leadership Required. Rising Tides Lift All Ships. Be Nice and Do Good.
Our Principles of Innovation: Arthur C Clarke's three Laws. Murphy's Law. Fail to Plan and Plan To Fail. Innovation is work. Innovation demands constraints. Innovation is not always new. Innovation rarely has a single author. Innovation shouldn't be the aim. Innovation isn't always good, and what's good is not always innovative. Innovation doesn't happen in a vacuum.
Our Principles of Business: Partner first, build second. Remember every contract or project has a child's life hanging in the balance. Always consider the diverse incentives and stakeholders in healthcare. NHS, Patient Registries, and basic research stay in a pre-competitive landscape. Never shelve a drug, or allow a license to do it.

Organizational Structure
While we may have a typical hierarchy in terms of corporate structure, our aim is to give each department/team enough autonomy and collaboration to accomplish their goals, take ownership and pride in their work, and leverage effective open communication. Typically, the larger an organization gets, the harder it is to change and the more arduous processes develop. Being a company of innovation, we will be particular about keeping teams small, supported, automating what is considered busy work, and only establish protocols and processes where we must.

Hiring Strategy
AlphaRose recognizes the need for a creative hiring strategy and an attractive employee package to successfully bring in the best talent in the industry. In order to secure innovative thinkers and doers, we aim to develop a multifaceted recruitment approach that emphasizes our commitment to cultivating a dynamic and collaborative work environment. This will include effective utilization of various online platforms, targeted outreach to universities and research institutions, as well as participation in industry-specific events and conferences. To differentiate ourselves from competitors, we see our mission as the most attractive component to hiring the right people AlphaRose needs. We also plan to offer a competitive employee package, encompassing competitive salaries, comprehensive healthcare benefits, stock options, bonuses, and opportunities for professional development and growth. By adopting this approach, we are confident in our ability to attract and retain top-tier employees, thereby fueling our success.

Financial Projections
$1B+ ANNUAL REVENUE. $20-100M ANNUAL REVENUE PER TREATMENT.
(Summary: High-level aggressive financial projection estimates showing over $1B in annual revenue after 8 years of commercial products. These projections hinge upon a Master File, batch trial, platform or process approval from regulatory bodies. Conservative projections can be delivered upon request. Financial expenses show a 26m cost per therapy product to approval, and a development timeline of 4-5 years. Phased inflection points will drastically decrease costs over time.)
Expenses: Preclinical Time: 1-2yrs. Clinical Trial time: 3-4yrs to conditional approval. Clinical Trial costs per patient: $300K. Average amount of patients in a Clinical Study - 12 (10% of population). Product Development Expenses: 26M.
Revenue: Revenue projections are initially based on a more traditional development path. As inflection points like batch trial approval and process approval by regulators are reached, revenue numbers are expected to grow exponentially, with cost of product to payers and patients to significantly come down.
Revenue Assumptions: Drug Pricing: $500k US | $300k EU | $150k ROW. Annual Patient Growth: 4x - 10x from undiagnosed / mis-diagnosed. Revenue towards donated product: 10%. 1.9b in annual revenue by year 8 of commercialization.

Fundraising Plan
Our fundraising plan is based on three rounds, with the first already completed. We are aiming to get to sustainable revenue post our Series A. We plan on using debt financing following our Series A if needed for additional expansion, with solid revenue numbers to justify low cost of capital.
2024 - 1m in PreSeed Investment | 8m Valuation. Core Team and CRO's established.
2025 - 5m Seed Round | 12m Valuation. Rosiphersen in Clinic. 5-10 more products in development. Al foundational structure established.
2026 - 30m - 40m Series A | (expected valuation 80-150m). Rosiphersen to Revenue. Additional products in the clinic. Al product development for ASO design and clinical endpoints.

Conclusion
The companies that have systems in place to produce inexpensive genetic treatments at scale, with technologies that create IP around processes and not solely on drugs, and with data to justify safety, will be poised for the largest market share of genetic medicines to come. The ones that continue to rely on traditional expensive drug development pipelines and population based approaches will plateau over the next five decades. Just like we've seen in other sectors with hotels and Airbnb as well as Yellow Taxi and Uber. AlphaRose is poised to be the new company to usher in this new era of medicine.

Contact Information:
Casey McPherson / CEO
casey@alpharose.com
512.940.4164
THIS IS A CONFIDENTIAL DOCUMENT AND CANNOT BE DISTRIBUTED, COPIED, OR TRANSMITTED IN ANYWAY UNLESS AUTHORIZED BY ITS OWNERS.
`;

